// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WindowsRestapi;
//
//    var dolgozo = Dolgozo.FromJson(jsonString);

namespace WindowsRestapi
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Dolgozo
    {
        [JsonConstructor]
        public Dolgozo(long id, string name, long salary)
        {
            Id = id;
            Name = name;
            Salary = salary;
        }

        public Dolgozo()
        {
        }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("salary")]
        public long Salary { get; set; }
        public override string ToString()
        {
            return Name;
        }
    }

    public partial class Dolgozo
    {
        public static List<Dolgozo> FromJson(string json) => JsonConvert.DeserializeObject<List<Dolgozo>>(json, WindowsRestapi.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Dolgozo> self) => JsonConvert.SerializeObject(self, WindowsRestapi.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
